# Generated by Django 3.1.13 on 2022-02-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('birthdate', models.DateField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('gender', models.BooleanField()),
            ],
        ),
    ]
